# Generated by Django 5.2.8 on 2025-11-27 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_job_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='post',
        ),
    ]
